### ISSUE TITLE
Panic seen with FST's Reader

### ISSUE THREAD

**Issue by abhinavdangeti** [couchbase/vellum#23]
Following panic observed with FST Reader:

```
panic: runtime error: index out of range
--
 
goroutine 13541 [running]:
panic(0xcc3ca0, 0x142f580)
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:540 +0x45e fp=0xc42ec19310 sp=0xc42ec19268 pc=0x42d32e
runtime.panicindex()
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:28 +0x5e fp=0xc42ec19330 sp=0xc42ec19310 pc=0x42be2e
github.com/couchbase/vellum.(*fstStateV1).atMulti(0xc42b4997c8, 0x7fc43c792082, 0x66d7a, 0x66e11, 0x4db45, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:191 +0x153 fp=0xc42ec19340 sp=0xc42ec19330 pc=0x580bd3
github.com/couchbase/vellum.(*fstStateV1).at(0xc42b4997c8, 0x7fc43c792082, 0x66d7a, 0x66e11, 0x4db45, 0x14, 0x14)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:123 +0x1f1 fp=0xc42ec193b8 sp=0xc42ec19340 pc=0x580731
github.com/couchbase/vellum.(*decoderV1).stateAt(0xc4336cd1d0, 0x4db45, 0x1266ac0, 0xc42b4997c8, 0x295e, 0xc42b4997c8, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:67 +0xb4 fp=0xc42ec19408 sp=0xc42ec193b8 pc=0x580474
github.com/couchbase/vellum.(*FST).get(0xc424974e60, 0xc422ffe090, 0x9, 0x10, 0x1266ac0, 0xc42b4997c8, 0xd14fc, 0xc4336cd140, 0x0, 0x1)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:83 +0x12c fp=0xc42ec19480 sp=0xc42ec19408 pc=0x583a3c
github.com/couchbase/vellum.(*Reader).Get(0xc42b4997c0, 0xc422ffe090, 0x9, 0x10, 0xc472921880, 0xc420c89678, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:253 +0x65 fp=0xc42ec194e0 sp=0xc42ec19480 pc=0x584655
github.com/blevesearch/bleve/index/scorch/segment/zap.(*Dictionary).postingsList(0xc4336cd1a0, 0xc422ffe090, 0x9, 0x10, 0x0, 0x0, 0xc472921880, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/dict.go:57 +0xee fp=0xc42ec19540 sp=0xc42ec194e0 pc=0x5a64de
github.com/blevesearch/bleve/index/scorch/segment/zap.(*Dictionary).PostingsList(0xc4336cd1a0, 0xc422ffe090, 0x9, 0x10, 0x0, 0x0, 0x0, 0xc472921880, 0xc472000101, 0xc420c89600, ...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/dict.go:46 +0x87 fp=0xc42ec19598 sp=0xc42ec19540 pc=0x5a6387
github.com/blevesearch/bleve/index/scorch.(*SegmentDictionarySnapshot).PostingsList(0xc431e37a20, 0xc422ffe090, 0x9, 0x10, 0x0, 0x0, 0x0, 0x1260cc0, 0xc472921880, 0x0, ...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/snapshot_segment.go:40 +0x7f fp=0xc42ec19600 sp=0xc42ec19598 pc=0x6089ff
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).TermFieldReader(0xc420476240, 0xc422ffe090, 0x9, 0x10, 0xc4320200b8, 0x4, 0x101, 0x40a2, 0xc433f10000, 0xc445b86770, ...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:423 +0x295 fp=0xc42ec196e0 sp=0xc42ec19600 pc=0x603dc5
github.com/blevesearch/bleve/search/searcher.NewTermSearcher(0x126b160, 0xc420476240, 0xc4320200d0, 0x9, 0xc4320200b8, 0x4, 0x3ff0000000000000, 0x0, 0xc44ad76000, 0x0, ...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/search/searcher/search_term.go:41 +0xbf fp=0xc42ec197c0 sp=0xc42ec196e0 pc=0x9de25f
github.com/blevesearch/bleve/search/query.(*TermQuery).Searcher(0xc45fe92150, 0x126b160, 0xc420476240, 0x12666a0, 0xc420753c80, 0x0, 0x12689a0, 0xc44ad76000, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/search/query/term.go:60 +0x99 fp=0xc42ec19828 sp=0xc42ec197c0 pc=0x9f4d09
github.com/blevesearch/bleve/search/query.(*ConjunctionQuery).Searcher(0xc45fe92090, 0x126b160, 0xc420476240, 0x12666a0, 0xc420753c80, 0xc422610000, 0x125e440, 0xc4949e3e40, 0xc422a8dd50, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/search/query/conjunction.go:58 +0x135 fp=0xc42ec19900 sp=0xc42ec19828 pc=0x9e3755
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc4203c6230, 0x12631c0, 0xc45fe92390, 0xc4400a2070, 0x0, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index_impl.go:458 +0x2c2 fp=0xc42ec19e58 sp=0xc42ec19900 pc=0xa01b82
github.com/couchbase/cbft.(*cacheBleveIndex).SearchInContext(0xc45fe92270, 0x12631c0, 0xc45fe92390, 0xc4400a2070, 0xc44d411ac0, 0xc444cd8800, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/goproj/src/github.com/couchbase/cbft/cache_bleve.go:110 +0x38a fp=0xc42ec19f18 sp=0xc42ec19e58 pc=0xb3f77a
github.com/blevesearch/bleve.MultiSearch.func1(0x126d500, 0xc45fe92270, 0xc4400a2070)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index_alias_impl.go:458 +0x152 fp=0xc42ec19fc8 sp=0xc42ec19f18 pc=0xa0a9d2
runtime.goexit()
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42ec19fd0 sp=0xc42ec19fc8 pc=0x45e8b1
created by github.com/blevesearch/bleve.MultiSearch
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index_alias_impl.go:465 +0x19d
```

More information here: https://issues.couchbase.com/browse/MB-29763

**Comment by abhinavdangeti** [comment]
Need to verify the possibility that multiple threads were accessing the same FST reader (The Reader does not support concurrency).

**Comment by abhinavdangeti** [comment]
Looks like multiple threads were accessing the same FST reader:

```
goroutine 13225 [running]:
panic(0xcc3ca0, 0x142f580)
	/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:540 +0x45e fp=0xc461b39310 sp=0xc461b39268 pc=0x42d32e
runtime.panicindex()
	/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:28 +0x5e fp=0xc461b39330 sp=0xc461b39310 pc=0x42be2e
github.com/couchbase/vellum.(*fstStateV1).atMulti(0xc447703908, 0x7fc4090f2b85, 0x10f71e, 0x10f7b6, 0x44b82, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:191 +0x153 fp=0xc461b39340 sp=0xc461b39330 pc=0x580bd3
github.com/couchbase/vellum.(*fstStateV1).at(0xc447703908, 0x7fc4090f2b85, 0x10f71e, 0x10f7b6, 0x44b82, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:123 +0x1f1 fp=0xc461b393b8 sp=0xc461b39340 pc=0x580731
github.com/couchbase/vellum.(*decoderV1).stateAt(0xc4336cd410, 0x44b82, 0x1266ac0, 0xc447703908, 0x0, 0xc447703908, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:67 +0xb4 fp=0xc461b39408 sp=0xc461b393b8 pc=0x580474
github.com/couchbase/vellum.(*FST).get(0xc424975040, 0xc429c966e8, 0x7, 0x8, 0x1266ac0, 0xc447703908, 0x20ba1d, 0xc4336cd380, 0x0, 0x1)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:83 +0x12c fp=0xc461b39480 sp=0xc461b39408 pc=0x583a3c
github.com/couchbase/vellum.(*Reader).Get(0xc447703900, 0xc429c966e8, 0x7, 0x8, 0xc453440440, 0xc461ffc8b8, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:253 +0x65 fp=0xc461b394e0 sp=0xc461b39480 pc=0x584655
```
FST Reader's pointer above: 0xc447703900, whose fstStateV1: {ptr: 0xc4336cd380}

```
goroutine 13497 [runnable]:
runtime.(*errorString).Error(0x142f580, 0xcc3ca0, 0x142f580)
	<autogenerated>:1 +0x8d fp=0xc488cd31f0 sp=0xc488cd31e8 pc=0x46165d
runtime.preprintpanics(0xc488cd32d8)
	/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:391 +0xb1 fp=0xc488cd3268 sp=0xc488cd31f0 pc=0x42cc61
panic(0xcc3ca0, 0x142f580)
	/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:532 +0x42a fp=0xc488cd3310 sp=0xc488cd3268 pc=0x42d2fa
runtime.panicindex()
	/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/panic.go:28 +0x5e fp=0xc488cd3330 sp=0xc488cd3310 pc=0x42be2e
github.com/couchbase/vellum.(*fstStateV1).atMulti(0xc447703908, 0x7fc4090f2b85, 0x10f71e, 0x10f7b6, 0x4690a, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:191 +0x153 fp=0xc488cd3340 sp=0xc488cd3330 pc=0x580bd3
github.com/couchbase/vellum.(*fstStateV1).at(0xc447703908, 0x7fc4090f2b85, 0x10f71e, 0x10f7b6, 0x4690a, 0x16, 0x16)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:123 +0x1f1 fp=0xc488cd33b8 sp=0xc488cd3340 pc=0x580731
github.com/couchbase/vellum.(*decoderV1).stateAt(0xc4336cd410, 0x4690a, 0x1266ac0, 0xc447703908, 0x1bed01, 0xc447703908, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/decoder_v1.go:67 +0xb4 fp=0xc488cd3408 sp=0xc488cd33b8 pc=0x580474
github.com/couchbase/vellum.(*FST).get(0xc424975040, 0xc431620008, 0x4, 0x8, 0x1266ac0, 0xc447703908, 0x1a1be5, 0xc4336cd380, 0x0, 0x1)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:83 +0x12c fp=0xc488cd3480 sp=0xc488cd3408 pc=0x583a3c
github.com/couchbase/vellum.(*Reader).Get(0xc447703900, 0xc431620008, 0x4, 0x8, 0xc422ee06c0, 0xc43ba0aa18, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/couchbase/vellum/fst.go:253 +0x65 fp=0xc488cd34e0 sp=0xc488cd3480 pc=0x584655
```
FST Reader's pointer above: 0xc447703900, whose fstStateV1: {ptr: 0xc4336cd380}

**Comment by steveyen** [comment]
hi @abhinavdangeti -- this might not be an issue with vellum, but more of the application (cbft / bleve) that's using vellum incorrectly?

**Comment by abhinavdangeti** [comment]
Hey @steveyen, that's correct - reason why I closed the issue here.
